services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - pg-network
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'finance_tracker'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - pg-network


volumes:
  postgres-db:

networks:
  pg-network:
    driver: bridge
